version: '2.2'
services:
  tomcat:
    container_name: tom
    image: tomcat:8.0
    mem_limit: 50m
    volumes:
      - /usr/local/tomcat/webapps:/usr/local/tomcat/webapps
      - /usr/local/tomcat/conf:/usr/local/tomcat/conf
    ports:
      - "80:8080"