version: '2.2'
services:
  tom:
    name: tom
    image: tomcat:8.0
    memory: 50m
    volumes:
      - /usr/local/tomcat/webapps:/usr/local/tomcat/webapps
      - /usr/local/tomcat/conf:/usr/local/tomcat/conf
    ports:
      - "80:8080"